
name: osmspliter
version: '3.9'

services:
  spliter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data-osm:/app/OSMs
    env_file:
      - .env
    command: >
      bash -c "rm -rf osm2pgrouting &&
               git clone https://github.com/pgRouting/osm2pgrouting.git && 
               mkdir temp && 
               cp ./osm2pgrouting/*.xml temp &&
               rm -rf osm2pgrouting &&
               mv temp osm2pgrouting &&
               su && apt update && apt list --upgradable && apt -f install && dpkg --configure -a && apt-get install osmium-tool &&
               chmod +x ./Modules/OSMTools/bin/osmconvert64 &&
               python Main.py"

volumes:
  data-osm:
    driver: local

